apiVersion: v1
kind: Service
metadata:
  name: coffeebean-supply-chain
spec:
  selector:
    app: coffeebean-supply-chain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer